	#ifndef __CLUCK2SESAME_PLATFORM_GENERALPURPOSEREGISTERS_INC
	#define __CLUCK2SESAME_PLATFORM_GENERALPURPOSEREGISTERS_INC
	#include "Platform.inc"

	radix decimal

	.module GENERALPURPOSEREGISTERS

	.externalVariable RA
	.externalVariable RAA
	.externalVariable RAB
	.externalVariable RAC
	.externalVariable RAD

	.externalVariable RB
	.externalVariable RBA
	.externalVariable RBB
	.externalVariable RBC
	.externalVariable RBD

	.externalVariable RZ
	.externalVariable RZA
	.externalVariable RZB

	#endif
