sudo: required

before_install:
  - sudo apt-get install libpopt-dev
  - sudo apt-get install flex
  - sudo apt-get install bison
  - sudo ./install-gputils.sh
  - sudo ./install-gpsim.sh

install: true

script:
  - make -C src all
  - cd src/firmware-tests
  - ./run.sh
