all:
	$(MAKE) -C gpsim2tuple all
	$(MAKE) -C randomise-ram all
	$(MAKE) -C lpf-rc all
	$(MAKE) -C mean all
	$(MAKE) -C trigonometry all
	$(MAKE) -C sunrise-sunset all
	$(MAKE) -C daylight-savings all

clean:
	$(MAKE) -C gpsim2tuple clean
	$(MAKE) -C randomise-ram clean
	$(MAKE) -C lpf-rc clean
	$(MAKE) -C mean clean
	$(MAKE) -C trigonometry clean
	$(MAKE) -C sunrise-sunset clean
	$(MAKE) -C daylight-savings clean
