%.o: %.asm
	$(AS) $(ASARGS) -o $@ $<

%.pp.o: %.asm 
	cat $< | sed "s/{{FIRMWARE_VER}}/$(FIRMWARE_VERSION)/g" > "`basename $< .asm`.pp.asm"
	$(AS) $(ASARGS) -o $@ "`basename $< .asm`.pp.asm"

%.a: %
	$(MAKE) -C $< all
